package config;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import util.PasswordUtil;

public final class Database {
  private static String jdbcUrl;

  private Database() { }

  public static synchronized void initialize() {
    if (jdbcUrl != null) return;
    try {
      Class.forName("org.h2.Driver");
      String configured = System.getProperty("shiftapp.dataDir");
      Path dataDir = configured == null || configured.isBlank()
          ? Path.of(System.getProperty("catalina.base", System.getProperty("java.io.tmpdir")), "data")
          : Path.of(configured);
      Files.createDirectories(dataDir);
      jdbcUrl = "jdbc:h2:file:" + dataDir.resolve("shiftapp").toAbsolutePath()
          + ";AUTO_SERVER=TRUE";
      try (Connection connection = getConnection()) {
        createSchema(connection);
        seed(connection);
      }
    } catch (Exception e) {
      jdbcUrl = null;
      throw new IllegalStateException("Failed to initialize database", e);
    }
  }

  public static Connection getConnection() throws SQLException {
    if (jdbcUrl == null) initialize();
    return DriverManager.getConnection(jdbcUrl, "sa", "");
  }

  private static void createSchema(Connection c) throws SQLException {
    String[] statements = {
      "CREATE TABLE IF NOT EXISTS branches (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS departments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS employment_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS app_settings (setting_key VARCHAR(80) PRIMARY KEY, setting_value VARCHAR(500) NOT NULL, description VARCHAR(500), updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS company_holidays (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, holiday_date DATE NOT NULL, branch_id BIGINT, name VARCHAR(100) NOT NULL, UNIQUE(holiday_date,branch_id), FOREIGN KEY(branch_id) REFERENCES branches(id))",
      "CREATE TABLE IF NOT EXISTS qualification_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_number VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, email VARCHAR(200) NOT NULL UNIQUE, password_hash VARCHAR(500) NOT NULL, hire_date DATE NOT NULL, branch_id BIGINT NOT NULL, department_id BIGINT NOT NULL, employment_type_id BIGINT NOT NULL, role VARCHAR(20) NOT NULL, locale VARCHAR(5) NOT NULL DEFAULT 'ja', active BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(branch_id) REFERENCES branches(id), FOREIGN KEY(department_id) REFERENCES departments(id), FOREIGN KEY(employment_type_id) REFERENCES employment_types(id))",
      "CREATE TABLE IF NOT EXISTS qualifications (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, expires_on DATE, active BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS work_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(30) NOT NULL UNIQUE, name_ja VARCHAR(50) NOT NULL, name_en VARCHAR(50) NOT NULL, start_time TIME, end_time TIME, crosses_midnight BOOLEAN NOT NULL DEFAULT FALSE, break_minutes INT NOT NULL DEFAULT 0, required_staff INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS shifts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, work_date DATE NOT NULL, work_type_code VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', note VARCHAR(500), updated_by BIGINT NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, work_date), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(updated_by) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS shift_change_requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, work_date DATE NOT NULL, requested_work_type VARCHAR(30) NOT NULL, reason VARCHAR(1000) NOT NULL, urgent BOOLEAN NOT NULL DEFAULT FALSE, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', decided_by BIGINT, decided_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(decided_by) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS leave_balances (user_id BIGINT PRIMARY KEY, days_remaining DECIMAL(6,2) NOT NULL DEFAULT 10, hourly_used INT NOT NULL DEFAULT 0, last_granted_on DATE, FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS leave_rule_config (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, effective_from DATE NOT NULL UNIQUE, attendance_threshold DECIMAL(4,3) NOT NULL DEFAULT 0.800, hourly_limit_days INT NOT NULL DEFAULT 5, hours_per_day INT NOT NULL DEFAULT 8, expiry_months INT NOT NULL DEFAULT 24, mandatory_days INT NOT NULL DEFAULT 5, active BOOLEAN NOT NULL DEFAULT TRUE)",
      "CREATE TABLE IF NOT EXISTS leave_grants (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, grant_date DATE NOT NULL, expires_on DATE NOT NULL, days_granted DECIMAL(6,2) NOT NULL, days_remaining DECIMAL(6,2) NOT NULL, attendance_rate DECIMAL(5,4), source VARCHAR(30) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,grant_date), FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS leave_consumptions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id BIGINT NOT NULL, grant_id BIGINT NOT NULL, days_used DECIMAL(6,3) NOT NULL, hours_used INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(request_id,grant_id), FOREIGN KEY(grant_id) REFERENCES leave_grants(id))",
      "CREATE TABLE IF NOT EXISTS leave_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, event_type VARCHAR(30) NOT NULL, event_date DATE NOT NULL, days DECIMAL(6,3) NOT NULL DEFAULT 0, hours INT NOT NULL DEFAULT 0, request_id BIGINT, grant_id BIGINT, note VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS leave_requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, leave_date DATE NOT NULL, leave_unit VARCHAR(20) NOT NULL, hours INT, reason VARCHAR(1000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', decided_by BIGINT, decided_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(decided_by) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS attendance (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, work_date DATE NOT NULL, clock_in TIMESTAMP, clock_out TIMESTAMP, in_lat DECIMAL(10,7), in_lng DECIMAL(10,7), out_lat DECIMAL(10,7), out_lng DECIMAL(10,7), location_status VARCHAR(30), status VARCHAR(20) NOT NULL DEFAULT 'OPEN', finalized BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE(user_id, work_date), FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS attendance_adjustments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, attendance_id BIGINT NOT NULL, requested_by BIGINT NOT NULL, requested_in TIMESTAMP, requested_out TIMESTAMP, reason VARCHAR(1000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', decided_by BIGINT, decided_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(attendance_id) REFERENCES attendance(id), FOREIGN KEY(requested_by) REFERENCES users(id), FOREIGN KEY(decided_by) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS delegations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, manager_id BIGINT NOT NULL, delegate_id BIGINT NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(manager_id) REFERENCES users(id), FOREIGN KEY(delegate_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS notifications (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(200) NOT NULL, message VARCHAR(1000) NOT NULL, target_url VARCHAR(500), is_read BOOLEAN NOT NULL DEFAULT FALSE, email_status VARCHAR(20) NOT NULL DEFAULT 'QUEUED', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS account_tokens (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, token VARCHAR(100) NOT NULL UNIQUE, token_type VARCHAR(20) NOT NULL, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id))",
      "CREATE TABLE IF NOT EXISTS mail_outbox (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recipient VARCHAR(200) NOT NULL, subject VARCHAR(300) NOT NULL, body VARCHAR(4000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'QUEUED', attempts INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, sent_at TIMESTAMP)",
      "CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id BIGINT, action VARCHAR(80) NOT NULL, target_type VARCHAR(80) NOT NULL, target_id VARCHAR(80), before_value CLOB, after_value CLOB, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(actor_id) REFERENCES users(id))"
    };
    try (Statement statement = c.createStatement()) {
      for (String sql : statements) statement.execute(sql);
      statement.execute("ALTER TABLE mail_outbox ADD COLUMN IF NOT EXISTS last_error VARCHAR(2000)");
      statement.execute("ALTER TABLE mail_outbox ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP");
      statement.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_work_days INT NOT NULL DEFAULT 5");
      statement.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_work_hours DECIMAL(5,2) NOT NULL DEFAULT 40");
      statement.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP");
      statement.execute("ALTER TABLE leave_consumptions ADD COLUMN IF NOT EXISTS restored BOOLEAN NOT NULL DEFAULT FALSE");
      statement.execute("ALTER TABLE qualifications ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE");
      statement.execute("ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_user_id BIGINT");
    }
  }

  private static void seed(Connection c) throws SQLException {
    if (count(c, "branches") == 0) {
      insertNames(c, "branches", new String[]{"本社", "北部支店", "中部支店", "那覇支店", "南部支店", "宮古支店", "石垣支店"});
      insertNames(c, "departments", new String[]{"営業部", "経理部", "総務部", "人事部"});
      insertNames(c, "employment_types", new String[]{"正社員", "契約社員", "パート", "アルバイト"});
    }
    if (count(c, "work_types") == 0) {
      String sql = "INSERT INTO work_types(code,name_ja,name_en,start_time,end_time,crosses_midnight,break_minutes,required_staff) VALUES(?,?,?,?,?,?,?,?)";
      try (PreparedStatement p = c.prepareStatement(sql)) {
        workType(p, "DAY", "日勤", "Day", "08:00:00", "17:00:00", false, 60, 5);
        workType(p, "NIGHT", "夜勤", "Night", "17:00:00", "08:00:00", true, 120, 7);
        workType(p, "OFF", "休み", "Off", null, null, false, 0, 0);
        workType(p, "LEAVE", "有休", "Paid leave", null, null, false, 0, 0);
        workType(p, "AM_LEAVE", "午前休", "AM leave", "13:00:00", "17:00:00", false, 0, 0);
        workType(p, "PM_LEAVE", "午後休", "PM leave", "08:00:00", "12:00:00", false, 0, 0);
      }
    }
    if (count(c, "users") == 0) {
      addUser(c, "HR001", "人事担当", "hr@example.com", "HR", 1, 4);
      addUser(c, "MG001", "那覇 店長", "manager@example.com", "MANAGER", 4, 1);
      addUser(c, "EM001", "山田 花子", "employee@example.com", "EMPLOYEE", 4, 1);
      addUser(c, "EM002", "佐藤 太郎", "sato@example.com", "EMPLOYEE", 4, 1);
      try (Statement s = c.createStatement()) {
        s.executeUpdate("INSERT INTO leave_balances(user_id,days_remaining,hourly_used,last_granted_on) SELECT id,10,0,CURRENT_DATE FROM users");
      }
    }
    if (count(c, "leave_rule_config") == 0) {
      try (Statement s = c.createStatement()) {
        s.executeUpdate("INSERT INTO leave_rule_config(effective_from,attendance_threshold,hourly_limit_days,hours_per_day,expiry_months,mandatory_days) VALUES(DATE '2019-04-01',0.800,5,8,24,5)");
      }
    }
    if (count(c, "app_settings") == 0) {
      String sql = "INSERT INTO app_settings(setting_key,setting_value,description) VALUES(?,?,?)";
      try (PreparedStatement p = c.prepareStatement(sql)) {
        setting(p, "SHIFT_SUBMISSION_DAY", "15", "翌月希望シフトの提出締切日");
        setting(p, "ALLOW_CONFIRM_WITH_WARNINGS", "true", "理由入力により警告付き確定を許可");
        setting(p, "LEAVE_ALLOW_PAST", "false", "過去日の有休申請を許可");
        setting(p, "LEAVE_MIN_NOTICE_DAYS", "0", "有休申請の最低事前日数");
        setting(p, "MONTHLY_CLOSE_DAY", "5", "翌月の勤怠締切日");
        setting(p, "RETENTION_YEARS", "5", "業務データ保存年数");
        setting(p, "LOCATION_REQUIRED", "false", "位置情報なしの打刻を禁止");
        setting(p, "MAX_CONCURRENT_USERS", "100", "想定最大同時利用者数");
      }
    }
    if (count(c, "leave_grants") == 0 && count(c, "users") > 0) {
      try (Statement s = c.createStatement()) {
        s.executeUpdate("INSERT INTO leave_grants(user_id,grant_date,expires_on,days_granted,days_remaining,attendance_rate,source) SELECT b.user_id,COALESCE(b.last_granted_on,CURRENT_DATE),DATEADD('MONTH',24,COALESCE(b.last_granted_on,CURRENT_DATE)),b.days_remaining,b.days_remaining,1.0,'MIGRATION' FROM leave_balances b WHERE b.days_remaining>0");
      }
    }
  }

  private static int count(Connection c, String table) throws SQLException {
    try (Statement s = c.createStatement(); ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM " + table)) {
      rs.next(); return rs.getInt(1);
    }
  }

  private static void insertNames(Connection c, String table, String[] names) throws SQLException {
    try (PreparedStatement p = c.prepareStatement("INSERT INTO " + table + "(name) VALUES(?)")) {
      for (String name : names) { p.setString(1, name); p.addBatch(); }
      p.executeBatch();
    }
  }

  private static void workType(PreparedStatement p, String code, String ja, String en,
      String start, String end, boolean overnight, int breakMinutes, int required) throws SQLException {
    p.setString(1, code); p.setString(2, ja); p.setString(3, en);
    p.setString(4, start); p.setString(5, end); p.setBoolean(6, overnight);
    p.setInt(7, breakMinutes); p.setInt(8, required); p.executeUpdate();
  }

  private static void addUser(Connection c, String number, String name, String email,
      String role, long branchId, long departmentId) throws SQLException {
    String sql = "INSERT INTO users(employee_number,name,email,password_hash,hire_date,branch_id,department_id,employment_type_id,role) VALUES(?,?,?,?,?,?,?,?,?)";
    try (PreparedStatement p = c.prepareStatement(sql)) {
      p.setString(1, number); p.setString(2, name); p.setString(3, email);
      p.setString(4, PasswordUtil.hash("Password1!"));
      p.setObject(5, LocalDate.of(2024, 4, 1)); p.setLong(6, branchId);
      p.setLong(7, departmentId); p.setLong(8, 1); p.setString(9, role); p.executeUpdate();
    }
  }

  private static void setting(PreparedStatement p, String key, String value, String description) throws SQLException {
    p.setString(1, key); p.setString(2, value); p.setString(3, description); p.executeUpdate();
  }
}
